# Generated by Django 5.2.7 on 2025-11-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='requester_email',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
