# Generated by Django 5.2.7 on 2025-11-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0002_servicerequest_requester_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='email_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='last_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='resolution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='requester_email',
            field=models.EmailField(max_length=255),
        ),
    ]
